import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { Wallet } from './near-wallet'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Contract } from '../near-interface'

const inter = Inter({ subsets: ['latin'] })
const CONTRACT_ID = 'dev-1672929464689-13020703704976'

export default function Home() {
  const [ useWeb3, setUseWeb3] = useState({})
  useEffect(()=> {
    const data = async() => {
      const wallet = await new Wallet({createAccessKeyFor: CONTRACT_ID}) // AGGTR , network = "mainnet"
      const contract = await new Contract({
        contractId: CONTRACT_ID,
        walletToUse: wallet,
      })

      const isSignedIn = await wallet.startUp()
      setUseWeb3({
        wallet,
        contract,
        isSignedIn
      })

    }
    data()
  }, []);
  console.log("useWeb3" , useWeb3)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
        <button onClick = {() => useWeb3.wallet.signIn()} >Connect Wallet</button>
        </div>

      </main>
    </>
  )
}
